# Generated by Django 5.2.7 on 2025-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='selected_rooms',
            field=models.TextField(),
        ),
    ]
