# Generated by Django 5.2.7 on 2025-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_roombooking_selected_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
